package SitesGUI;

import Models.SiteInfo.Site;
import Models.SiteInfo.SiteCollection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the` template in the editor.
 */

/**
 *
 * @author hp
 */
public class DisplaySitesInformation extends javax.swing.JFrame {
    SiteCollection sites;
    /**
     * Creates new form DisplaySitesInformation
     */
    public DisplaySitesInformation(){
        try {
            initComponents();
            updateTable();
        } catch (SQLException ex) {
            Logger.getLogger(DisplaySitesInformation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void updateTable() throws SQLException {
         System.out.println("beging");
        ArrayList<Site> sitesList = sites.getAllSitesData();
         System.out.println("right after returning the list");
        DefaultTableModel model = (DefaultTableModel) TableDisplaySites_jTable.getModel();
        System.out.println("before objects");
        Object[] row = new Object[11];
        for(int i=0; i<sitesList.size(); ++i){
            row[0] = sitesList.get(i).getCode_Site();
            row[1] = sitesList.get(i).getClient();
            row[2] = sitesList.get(i).getSite_Type();
            row[3] = sitesList.get(i).getSite_Metrage();
            row[4] = sitesList.get(i).getCity();
            row[5] = sitesList.get(i).getAdress();
            row[6] = sitesList.get(i).getFarend();
            row[7] = sitesList.get(i).getAzimut();
            row[8] = sitesList.get(i).getTechnology();
            row[9] = sitesList.get(i).getLongitude()+" / "+sitesList.get(i).getLatitude();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDisplaySites_jTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 3, 36)); // NOI18N
        jLabel1.setText("Tout les Sites");

        TableDisplaySites_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code du Site", "Client", "Type de Site", "Metrage", "Ville", "Adress", "Farend", "Azimut", "Technology", "Logitude/Latitude"
            }
        ));
        jScrollPane1.setViewportView(TableDisplaySites_jTable);

        jTabbedPane1.addTab("Info General du Site", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel1)
                .addContainerGap(499, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplaySitesInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplaySitesInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplaySitesInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplaySitesInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplaySitesInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableDisplaySites_jTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
