package SitesGUI;

import MenueGUI.MainMenue_Admin;
import MenueGUI.MainMenue_Normal;
import Models.SiteInfo.Site;
import Models.User.User;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hp
 */
public class NewSite extends javax.swing.JFrame {

    User current_User;
    ArrayList<Site> sites;
    Statement myStmt;
    Connection myCon;
    ResultSet rs;
    private Site current_site;

    /**
     * Creates new form SiteInfo
     */
    public NewSite() {
        initComponents();
    }

    public NewSite(User current_User) throws SQLException {
        initComponents();
        this.current_site = current_site;
        UserInfo_Label.setText(current_User.getUsername());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        Main_Title_Label = new javax.swing.JLabel();
        Code_Site_TextField = new javax.swing.JTextField();
        Code_Site_Label = new javax.swing.JLabel();
        Adress_Label = new javax.swing.JLabel();
        Adress_TextField = new javax.swing.JTextField();
        Longitude_Label = new javax.swing.JLabel();
        Longitude_TextField = new javax.swing.JTextField();
        Latitude_Label = new javax.swing.JLabel();
        Latitude_TextField = new javax.swing.JTextField();
        Client_Lable = new javax.swing.JLabel();
        Client_TextFlied = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Code_Site_Label2 = new javax.swing.JLabel();
        Farend_Label = new javax.swing.JLabel();
        Farend__TextFlied = new javax.swing.JTextField();
        Azimut_Label = new javax.swing.JLabel();
        Azimut_TextFlied = new javax.swing.JTextField();
        Save_Button = new javax.swing.JButton();
        Clear_Button = new javax.swing.JButton();
        Adress_Label1 = new javax.swing.JLabel();
        Ville_TextField = new javax.swing.JTextField();
        Metrage_label = new javax.swing.JLabel();
        Metrage_TextFlied = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Home_Button = new javax.swing.JButton();
        Technology_TextField = new javax.swing.JTextField();
        TypeSite_TextField = new javax.swing.JTextField();
        UserInfo_Label = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Main_Title_Label.setFont(new java.awt.Font("Gill Sans MT", 3, 24)); // NOI18N
        Main_Title_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Main_Title_Label.setText("Informations Relatives au Site");
        Main_Title_Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        Code_Site_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Code_Site_TextFieldActionPerformed(evt);
            }
        });

        Code_Site_Label.setText("Code du Site");

        Adress_Label.setText("Ville");

        Longitude_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Longitude_Label.setText("Longitude");

        Latitude_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Latitude_Label.setText("Latitude");

        Client_Lable.setText("Client");

        Client_TextFlied.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Client_TextFliedActionPerformed(evt);
            }
        });

        jLabel5.setText("Type de Site");

        Code_Site_Label2.setText("Technology");

        Farend_Label.setText("Farend");

        Azimut_Label.setText("Azimut");

        Save_Button.setText("Enregistrer");
        Save_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_ButtonActionPerformed(evt);
            }
        });

        Clear_Button.setText("Effacer");
        Clear_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_ButtonActionPerformed(evt);
            }
        });

        Adress_Label1.setText("Adress");

        Ville_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ville_TextFieldActionPerformed(evt);
            }
        });

        Metrage_label.setText("Metrage");

        Home_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home.png"))); // NOI18N
        Home_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Home_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Save_Button)
                .addGap(18, 18, 18)
                .addComponent(Clear_Button)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(Main_Title_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UserInfo_Label)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Azimut_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Azimut_TextFlied, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Code_Site_Label)
                                    .addComponent(Adress_Label)
                                    .addComponent(jLabel5)
                                    .addComponent(Adress_Label1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TypeSite_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Adress_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Ville_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Code_Site_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(Client_Lable))
                                    .addComponent(Longitude_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Client_TextFlied, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(Longitude_TextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Latitude_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Code_Site_Label2)
                                    .addComponent(Farend_Label)
                                    .addComponent(Metrage_label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Latitude_TextField)
                                    .addComponent(Farend__TextFlied)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(Metrage_TextFlied, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Technology_TextField, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(UserInfo_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Main_Title_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Code_Site_Label)
                    .addComponent(Client_Lable)
                    .addComponent(Client_TextFlied, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Code_Site_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Longitude_Label)
                    .addComponent(Longitude_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ville_TextField)
                    .addComponent(Adress_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Latitude_Label)
                    .addComponent(Latitude_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Adress_TextField)
                    .addComponent(Adress_Label1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(TypeSite_TextField))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Code_Site_Label2)
                        .addComponent(Technology_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Azimut_Label)
                        .addComponent(Azimut_TextFlied, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Farend__TextFlied, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Farend_Label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Metrage_TextFlied, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Metrage_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Clear_Button)
                            .addComponent(Save_Button))
                        .addGap(45, 45, 45))
                    .addComponent(Home_Button, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Code_Site_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Code_Site_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Code_Site_TextFieldActionPerformed

    private void Client_TextFliedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Client_TextFliedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Client_TextFliedActionPerformed

    private void Ville_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ville_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ville_TextFieldActionPerformed

    private void Clear_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_ButtonActionPerformed
        // TODO add your handling code here:
        Clear_Button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                Code_Site_TextField.setText("");
                Client_TextFlied.setText("");
                Ville_TextField.setText("");
                Longitude_TextField.setText("");
                Latitude_TextField.setText("");
                Adress_TextField.setText("");
                Azimut_TextFlied.setText("");
                Farend__TextFlied.setText("");

            }
        });
    }//GEN-LAST:event_Clear_ButtonActionPerformed

    private void Save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_ButtonActionPerformed
        // TODO add your handling code here:
        Save_Button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                try {
                    myCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/testtradivtel", "root", "");
                    myStmt = myCon.createStatement();

                    String codeTemp = Code_Site_TextField.getText();
                    String villeTemp = Ville_TextField.getText();
                    String clientTemp = Client_TextFlied.getText();
                    String adressTemp = Adress_TextField.getText();
                    String typeSiteTemp = TypeSite_TextField.getText();
                    String longitudeTemp = Longitude_TextField.getText();
                    String latitudeTemp = Latitude_TextField.getText();
                    String Technology = Technology_TextField.getText();
                    String farendTemp = Farend__TextFlied.getText();
                    String AzimutTemp = Azimut_TextFlied.getText();
                    String metragetempstring = Metrage_TextFlied.getText();
                    System.out.println(metragetempstring);
                    Double metrageTemp = Double.parseDouble(metragetempstring);
                    System.out.println(metrageTemp);

                    String query = "INSERT INTO `sites` "
                            + "(`Code_Site`, `Client`, `Ville`, `Adress`, `Type_Site`, `Longitude`, `Latitude`, `Technology`, `Farend`, `Azimut`, `Metrage`) "
                            + "VALUES ('" + codeTemp + "', '" + clientTemp + "', '" + villeTemp + "', '" + adressTemp + "', '" + typeSiteTemp + "', '" + longitudeTemp + "', '" + latitudeTemp + "', '" + Technology + "', "
                            + "'" + farendTemp + "', '" + AzimutTemp + "', '" + metrageTemp + "');";
                    myStmt.execute(query);

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }

            }
        });
    }//GEN-LAST:event_Save_ButtonActionPerformed

    private void Home_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_ButtonActionPerformed
        // TODO add your handling code here:
        Home_Button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (current_User.getAccountType().equals("Admin")) {
                    dispose();
                    new MainMenue_Admin(current_User).setVisible(true);
                } else {
                    dispose();
                    new MainMenue_Normal(current_User).setVisible(true);
                }

            }
        });
    }//GEN-LAST:event_Home_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewSite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewSite().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adress_Label;
    private javax.swing.JLabel Adress_Label1;
    private javax.swing.JTextField Adress_TextField;
    private javax.swing.JLabel Azimut_Label;
    private javax.swing.JTextField Azimut_TextFlied;
    private javax.swing.JButton Clear_Button;
    private javax.swing.JLabel Client_Lable;
    private javax.swing.JTextField Client_TextFlied;
    private javax.swing.JLabel Code_Site_Label;
    private javax.swing.JLabel Code_Site_Label2;
    private javax.swing.JTextField Code_Site_TextField;
    private javax.swing.JLabel Farend_Label;
    private javax.swing.JTextField Farend__TextFlied;
    private javax.swing.JButton Home_Button;
    private javax.swing.JLabel Latitude_Label;
    private javax.swing.JTextField Latitude_TextField;
    private javax.swing.JLabel Longitude_Label;
    private javax.swing.JTextField Longitude_TextField;
    private javax.swing.JLabel Main_Title_Label;
    private javax.swing.JTextField Metrage_TextFlied;
    private javax.swing.JLabel Metrage_label;
    private javax.swing.JButton Save_Button;
    private javax.swing.JTextField Technology_TextField;
    private javax.swing.JTextField TypeSite_TextField;
    private javax.swing.JLabel UserInfo_Label;
    private javax.swing.JTextField Ville_TextField;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
