package SitesGUI;

import MenueGUI.MainMenue_Admin;
import MenueGUI.MainMenue_Normal;
import Models.SiteInfo.SiteCollection;
import Models.User.User;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hp
 */
public class SearchSites extends javax.swing.JFrame {

    User current_User;

    /**
     * Creates new form SearchSites
     */
    public SearchSites() {
        initComponents();
    }

    public SearchSites(User current_User) {
        initComponents();
        this.current_User = current_User;
        UserInfo_Label.setText(current_User.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Search_Button = new javax.swing.JButton();
        MainTitle_Lalbel = new javax.swing.JLabel();
        SearchQuery_TextField = new javax.swing.JTextField();
        SearchParam_ComboBox = new javax.swing.JComboBox<>();
        Home_Button = new javax.swing.JButton();
        UserInfo_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Search_Button.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Search_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        Search_Button.setText("Chercher");
        Search_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_ButtonActionPerformed(evt);
            }
        });

        MainTitle_Lalbel.setFont(new java.awt.Font("Gill Sans MT", 3, 36)); // NOI18N
        MainTitle_Lalbel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainTitle_Lalbel.setText("Recherche de site");

        SearchQuery_TextField.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SearchQuery_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchQuery_TextFieldActionPerformed(evt);
            }
        });

        SearchParam_ComboBox.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        SearchParam_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Code_Site", "Client", "Ville", "Type_Site" }));
        SearchParam_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchParam_ComboBoxActionPerformed(evt);
            }
        });

        Home_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home.png"))); // NOI18N
        Home_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SearchParam_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Search_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(MainTitle_Lalbel, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(201, 201, 201))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SearchQuery_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Home_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(UserInfo_Label)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserInfo_Label)
                .addGap(45, 45, 45)
                .addComponent(MainTitle_Lalbel)
                .addGap(18, 18, 18)
                .addComponent(SearchQuery_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Search_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchParam_ComboBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(Home_Button))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchQuery_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchQuery_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchQuery_TextFieldActionPerformed

    private void Search_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_ButtonActionPerformed
        // TODO add your handling code here:
        Search_Button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                String searchQueryString = SearchQuery_TextField.getText();
                String param_Search = SearchParam_ComboBox.getSelectedItem().toString();
                //switch()

                System.out.println(searchQueryString + " " + param_Search);
                SiteCollection sites_temp = new SiteCollection();
                ResultSet rs;
                rs = sites_temp.SearchSites(searchQueryString, param_Search);

                if (rs == null) {
                    JOptionPane.showMessageDialog(null, "Aucun resultat trouve");
                } else {
                    try {
                        new DisplaySites(rs, current_User).setVisible(true);
                        dispose();
                    } catch (SQLException ex) {
                        Logger.getLogger(SearchSites.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
        );
    }//GEN-LAST:event_Search_ButtonActionPerformed

    private void Home_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_ButtonActionPerformed
        // TODO add your handling code here:
        Home_Button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (current_User.getAccountType().equals("Admin")) {
                    dispose();
                    new MainMenue_Admin(current_User).setVisible(true);
                } else {
                    dispose();
                    new MainMenue_Normal(current_User).setVisible(true);
                }

            }
        });

    }//GEN-LAST:event_Home_ButtonActionPerformed

    private void SearchParam_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchParam_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchParam_ComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchSites.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchSites.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchSites.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchSites.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchSites().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home_Button;
    private javax.swing.JLabel MainTitle_Lalbel;
    private javax.swing.JComboBox<String> SearchParam_ComboBox;
    private javax.swing.JTextField SearchQuery_TextField;
    private javax.swing.JButton Search_Button;
    private javax.swing.JLabel UserInfo_Label;
    // End of variables declaration//GEN-END:variables
}
